### ISSUE TITLE
Old UltiSnip snippets not being provided

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc-snippets#1]
For snippets I had

```
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'

:CocInstall coc-ultisnips
```

I changed that to

```
Plug 'honza/vim-snippets'

:CocUninstall coc-ultisnips
:CocInstall coc-snippets
```
The `~/.vim/plugged/vim-snippets` provides the `UltiSnips` directory, but coc-snippets isn't providing any snippets by itself.

**Comment by chemzqm** [comment]
You need to upgrade coc to latest master.

**Comment by oblitum** [comment]
I've just upgraded, still same behavior as above.

**Comment by oblitum** [comment]
To be more exact, this is my changeset:

```diff
diff --git a/.vimrc b/.vimrc
index bf47dfd..9fa1b0f 100644
--- a/.vimrc
+++ b/.vimrc
@@ -126,7 +126,6 @@ Plug 'oblitum/formatvim', {'on': []}
 Plug 'KabbAmine/zeavim.vim'
 " }}}
 " Snippets {{{
-Plug 'SirVer/ultisnips', {'do': function('PlugRemotePlugins')}
 Plug 'honza/vim-snippets'
 " }}}
 " Diagnostics {{{
@@ -143,8 +142,8 @@ let s:coc_extensions = [
 \   'coc-vetur',
 \   'coc-eslint',
 \   'coc-prettier',
-\   'coc-tsserver',
-\   'coc-ultisnips'
+\   'coc-snippets',
+\   'coc-tsserver'
 \ ]
 Plug 'neoclide/coc-neco'
 Plug 'neoclide/coc.nvim', {'do': function('PlugCoc')}
@@ -1683,10 +1682,6 @@ nmap <silent> <leader><cr> <Plug>(quickrun)
 " vim-vebugger {{{
 let g:vebugger_leader = '<leader>v'
 " }}}
-" Snippets
-" ultisnips {{{
-let g:UltiSnipsExpandTrigger = '<c-space>s'
-" }}}
 " Diagnostics
 " coc.nvim {{{
 nmap     <silent>       <leader>cf <Plug>(coc-format)
@@ -1706,6 +1701,7 @@ nmap     <silent>       <leader>co <Plug>(coc-openlink)
 nmap     <silent>       <leader>cq <Plug>(coc-fix-current)
 nnoremap <silent>       <leader>ch :call CocActionAsync('highlight')<cr>
 nnoremap <silent>       <leader>cH :call CocActionAsync('doHover')<cr>
+imap     <silent>       <c-space>s <Plug>(coc-snippets-expand)
 inoremap <silent><expr> <c-space>r coc#refresh()
 " }}}
 " }}}
```

**Comment by oblitum** [comment]
`time` and `box` snippets are working indeed. But not the ones from `/home/francisco/.vim/plugged/vim-snippets/UltiSnips/cpp.snippets`.

**Comment by fannheyward** [comment]
@chemzqm no.

```
`!p
box = make_box(len(t[1]))
snip.rv = box[0]
snip += box[1]
``!p
box = make_box(len(t[1]))
snip.rv = box[2]
snip += box[3]`
```

and `:call coc#rpc#notify('doKeymap', ['snippets-expand'])`

**Comment by oblitum** [comment]
By the way, I could trigger `time` and `box` from the popup, I couldn't trigger it with my `+imap     <silent>       <c-space>s <Plug>(coc-snippets-expand)` in the diff above.

**Comment by chemzqm** [comment]
>  But not the ones from /home/francisco/.vim/plugged/vim-snippets/UltiSnips/cpp.snippets.

You need to spcifiy `extends` configuration for `cpp`,
maybe I should respect extends in snippet files.

**Comment by chemzqm** [comment]
@

> @chemzqm no.
> 
> ```
> `!p
> box = make_box(len(t[1]))
> snip.rv = box[0]
> snip += box[1]
> ``!p
> box = make_box(len(t[1]))
> snip.rv = box[2]
> snip += box[3]`
> ```
> and `:call coc#rpc#notify('doKeymap', ['snippets-expand'])`

Seems the parser is broken for you, have no idea.

**Comment by oblitum** [comment]
> You need to spcifiy `extends` configuration for `cpp`,
> maybe I should respect extends in snippet files.

Ah yeah, iirc the honza cpp snippets extends the c ones...

**Comment by oblitum** [comment]
Anyway, I'll configure that manually (or wait for the fix), but, I can't still expand through trigger.

**Comment by chemzqm** [comment]
The expand trigger expect strict match, what's the output after you trigger expand?

**Comment by oblitum** [comment]
I get `No match snippets found`, even after `box` or `time`.

**Comment by oblitum** [comment]
By the way, better write `No matching snippets found` there.

**Comment by chemzqm** [comment]
The box could works at line begin, could you try it at beginning of line?

**Comment by oblitum** [comment]
@chemzqm didn't work.

**Comment by chemzqm** [comment]
Does it work on confirm completion?

**Comment by fannheyward** [comment]
Reinstall coc-snippets and coc, still not working...

**Comment by oblitum** [comment]
C++ has some range-for snippets that don't exist for C, was provided by previous UltiSnip setup, not now (after extend).

**Comment by oblitum** [comment]
Sorry, I'll have to leave now for sleep...

**Comment by chemzqm** [comment]
> was provided by previous UltiSnip setup, not now (after extend).

There's a bug with overwrite for extends filetypes.

**Comment by chemzqm** [comment]
> Reinstall coc-snippets and coc, still not working...

I think I got the reason, the file you've checkout use `\r` for line ending, not `\n`, the parser need to fix.

**Comment by chemzqm** [comment]
Should be fixed now.

**Comment by oblitum** [comment]
I still have the same issues inside a c++ file sample:

- no `cpp` snippets without extends conf.
- only some `c` snippets with extends conf.
- can't expand `time` with `imap <silent> <c-space>s <Plug>(coc-snippets-expand)`.
- only `time`, `box` and a few general snippets show up in completion menu, they can only expand through menu confirmation.

**Comment by oblitum** [comment]
I tried this plugin again, and the issue that I didn't strike out above is still present: "only some `c` snippets". I'm using `call coc#config('snippets.extends', { 'cpp' : ['c'] })`, snippets are working fine, but I'm not getting c++ snippets in the popup, like `forr` and `fore`, just `for` and `fori` that come from `c`, in the honza snippet set.

**Comment by oblitum** [comment]
Snippets for `tex`, like this from honza:

```
snippet "b(egin)?" "begin{} / end{}" br
\begin{${1:something}}
	${0:${VISUAL}}
\end{$1}
endsnippet
```
Also don't work.

**Comment by chemzqm** [comment]
> Snippets with patters, like this for `tex` from honza:

You should be able to expand the expression snippet.
Most patterns can't be converted to prefix that can be shown in pupup menu, one possible is conver it to context snippet instead, but context snippet is not supported yet.

**Comment by chemzqm** [comment]
> I'm not getting c++ snippets in the popup, like `forr` and `fore`, just `for` and `fori` that come from `c`, in the honza snippet set.

forr` and `fore` are defined as snipmate snippets, ultisnips could load them, but it's not supported by coc-snippets yet.

**Comment by oblitum** [comment]
oh thanks, I had no idea about that. Guess it's about time to write my own snippets.

**Comment by oblitum** [comment]
@chemzqm this could be listed in README as some of the UltiSnips features not yet supported.

**Comment by oblitum** [comment]
ops, nevermind, it's listed already.
