### ISSUE TITLE
errors in ultisnips snippets

### ISSUE THREAD

**Issue by nmxiao** [neoclide/coc-snippets#109]
I use windows 10  + Neovim 0.4.3, when I use the following markdown snippets:

```
global !p
texMathZones = ['texMathZone'+x for x in ['A', 'AS', 'B', 'BS', 'C', 'CS', 'D', 'DS', 'E', 'ES', 'F', 'FS', 'G', 'GS', 'H', 'HS', 'I', 'IS', 'J', 'JS', 'K', 'KS', 'L', 'LS', 'DS', 'V', 'W', 'X', 'Y', 'Z']]

texIgnoreMathZones = ['texMathText']

texMathZoneIds = vim.eval('map('+str(texMathZones)+", 'hlID(v:val)')")
texIgnoreMathZoneIds = vim.eval('map('+str(texIgnoreMathZones)+", 'hlID(v:val)')")

ignore = texIgnoreMathZoneIds[0]

def math():
	synstackids = vim.eval("synstack(line('.'), col('.') - (col('.')>=2 ? 1 : 0))")
	try:
		first = next(i for i in reversed(synstackids) if i in texIgnoreMathZoneIds or i in texMathZoneIds)
		return first != ignore
	except StopIteration:
		return False
		
def nomath():
	synstackids = vim.eval("synstack(line('.'), col('.') - (col('.')>=2 ? 1 : 0))")
	try:
		first = next(i for i in reversed(synstackids) if i in texIgnoreMathZoneIds or i in texMathZoneIds)
		return first == ignore
	except StopIteration:
		return True
endglobal

snippet mk "Math" wA
$${1}$`!p
if t[2] and t[2][0] not in [',', '.', '?', '-', ' ']:
	snip.rv = ' '
else:
	snip.rv = ''
`$2
endsnippet

context "math()"
snippet => "implies" Ai
\implies
endsnippet
```

when I input trigger 'mk', it shows the error "name 'snip' is not defined"
when I input trigger '=>' in the math, it shows the error " name 'ContextSnippet' is not defined".

The errors only occurs using coc-snippets.
When I use Ultisnips + coc-ultisnips plugins, it runs well without any errors.

Thanks.

**Comment by chemzqm** [comment]
Please upgrade coc-snippets and provide result from `:CocCommand workspace.showOutput snippets
`

**Comment by CollinsPeriodLee** [comment]
I use the same snippets and have similar issues, but with different error dumped.
Results from `:CocCommand workspace.showOutput snippets`
![](https://i.imgur.com/ckGoE9m.png)
Results dumped in the command line are
![](https://i.imgur.com/jr9dNNz.png)

**Comment by chemzqm** [comment]
@CollinsPeriodLee Can't reproduce, please provide snippet you're using.

**Comment by CollinsPeriodLee** [comment]
```
snippet mk "Math" wA
$${1}$`!p
if t[2] and t[2][0] not in [',', '.', '?', '-', ' ']:
	snip.rv = ' '
else:
	snip.rv = ''
`$2
endsnippet
```

**Comment by CollinsPeriodLee** [comment]
Here, I only use coc-snippets plugin. I didn't use coc-ultisnips and Ultisnips.

**Comment by chemzqm** [comment]
Please upgrade coc-snippets and provide result from `:CocCommand workspace.showOutput snippets`

**Comment by CollinsPeriodLee** [comment]
```
 [Info 8:58:31 AM] Using ultisnips directories: UltiSnips /home/lizuol/.config/coc/ultisnips
 [Info 8:58:31 AM] Using ultisnips python command: pyx
```

**Comment by CollinsPeriodLee** [comment]
And One more thing, for this snippet,
```
 priority 100                 
 snippet ... "ldots" iA       
 \ldots                        
 endsnippet  
```
the trigger words become a single `.` rather than 3 dots `...`

Thank you a lot.

**Comment by CollinsPeriodLee** [comment]
The error dumped in command line is
```
[coc.nvim] error: UnhandledRejection: request error nvim_call_function - Vim(return):Error invoking 
'python_eval' on channel 4 (python3-script-host):
error caught in request handler 'python_eval ['snip.rv']':
Traceback (most recent call last):
  File "/home/lizuol/anaconda3/lib/python3.7/site-packages/pynvim/plugin/script_host.py", line 169, 
in python_eval
    return eval(expr, self.module.__dict__)
  File "<string>", line 1, in <module>
AttributeError: 'ContextSnippet' object has no attribute 'rv'
Error: request error nvim_call_function - Vim(return):Error invoking 'python_eval' on channel 4 (pyt
hon3-script-host):
error caught in request handler 'python_eval ['snip.rv']':
Traceback (most recent call last):
  File "/home/lizuol/anaconda3/lib/python3.7/site-packages/pynvim/plugin/script_host.py", line 169, 
in python_eval
    return eval(expr, self.module.__dict__)
  File "<string>", line 1, in <module>
AttributeError: 'ContextSnippet' object has no attribute 'rv'
    at /home/lizuol/.local/share/nvim/plugged/coc.nvim/build/index.js:14243:32
    at NvimTransport.parseMessage (/home/lizuol/.local/share/nvim/plugged/coc.nvim/build/index.js:10
847:17)
    at DecodeStream.<anonymous> (/home/lizuol/.local/share/nvim/plugged/coc.nvim/build/index.js:1081
7:18)
    at DecodeStream.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at DecodeStream.Readable.push (_stream_readable.js:214:10)
    at DecodeStream.Transform.push (_stream_transform.js:152:32)
    at DecodeBuffer.DecodeStream.decoder.push (/home/lizuol/.local/share/nvim/plugged/coc.nvim/build
/index.js:13767:12)
    at DecodeBuffer.flush (/home/lizuol/.local/share/nvim/plugged/coc.nvim/build/index.js:12757:12)
```

**Comment by danielfalbo** [comment]
I'm getting that weird error too! Try [this tex.snippets](https://raw.githubusercontent.com/gillescastel/latex-snippets/master/tex.snippets) to reproduce

**Comment by danielfalbo** [comment]
While in neovim some random times the snippets do what they're supposed to and some other random times they produce the weird error, in vim there are no errors but some snippets never work.

Some snippets like
```
snippet / "Fraction" i
\\frac{${VISUAL}}{$1}$0
endsnippet
```
and
```
context "math()"
snippet td "to the ... power" iA
^{$1}$0
endsnippet
```
are silently non-working in vim and producing the weird terrible error but sometimes working in neovim.

The "math()" context is the same as the one in the original post of this issue.

**Comment by chemzqm** [comment]
Fixed on latest coc-snippets.

**Comment by stokhos** [comment]
@CollinsPeriodLee @danielfalbo Do you have this error after upgrading to latest version? 
On my computer I'm still having this problem.

**Comment by danielfalbo** [comment]
On my machine I get a different error now: 
![Screenshot 2020-11-19 at 05 48 51](https://user-images.githubusercontent.com/39460524/99622676-edb53180-2a2a-11eb-9eaa-9ad02d3f6c3b.png)

Anyway I noticed that the whole thing is a lot smoother and I get the error less frequently than before the update.

**Comment by chemzqm** [comment]
@danielfalbo I can't reproduce, need snippet you're using.

**Comment by danielfalbo** [comment]
https://github.com/danielfalbo/dotfiles/blob/master/config/nvim/snippets/tex.snippets these are my tex snippets. To reproduce edit a new .tex file and: 
![Screen-Recording-2020-11-19-at-0](https://user-images.githubusercontent.com/39460524/99643739-5ad9be80-2a4d-11eb-9912-3d00eb274840.gif)

**Comment by stokhos** [comment]
I'm still having this problem occasionally. But like what danielfalbo said, it shows up less frequently.

I'm using same math snippet, and this problems shows up randomly, and I couldn't find a way to effectively trigger this bug.

**Comment by fecet** [comment]
Same problem occurs for me always, not randomly

**Comment by Joellidin** [comment]
I also get this issue

**Comment by zhuosongz** [comment]
Same issue here.

**Comment by ihasdapie** [comment]
Same issue here with this snippet

```
snippet / "Fraction" i
\\frac{${VISUAL}}{$1}$0
endsnippet
```
Typing `6/` produces this error:

```
 \frac{Traceback (most recent call last):
  File "<string>", line 3, in <module>
AttributeError: 'ContextSnippet' object has no attribute '_reset'}{} $$
```

**Comment by ihasdapie** [comment]
I just tried it again and realized I was providing the wrong snippet.

Here is the one that produces the error:

```
priority 1000
context "math()"
snippet '^.*\)/' "() frac" wrA
`!p
# stripped = match.string[:-1]
stripped = match.string[:-1].replace('\frac', '\\frac') # so that this will work with coc-snippets
depth = 0
i = len(stripped) - 1
while True:
	if stripped[i] == ')': depth += 1
	if stripped[i] == '(': depth -= 1
	if depth == 0: break;
	i-=1
snip.rv = stripped[0:i] + "\\frac{" + stripped[i+1:-1] + "}"
`{$1}$0
endsnippet

```


I just tried it again and the issue comes up only when I trigger the snippet *before* the completion menu pops up, i.e. if I do `(xxx)/` fast, it breaks with the above error. However if I wait until the completion menu loads until triggering the snippet it works fine.

**Comment by chemzqm** [comment]
Can't reproduce, please try minimal vimrc.

**Comment by chemzqm** [comment]
> I use the same snippets and have similar issues, but with different error dumped. Results from `:CocCommand workspace.showOutput snippets` ![](https://camo.githubusercontent.com/3ded714adbebd4c13c204a9b4ee421c8371f6e8745e8db1bb8e7625324a1e95d/68747470733a2f2f692e696d6775722e636f6d2f636b476f45396d2e706e67) Results dumped in the command line are ![](https://camo.githubusercontent.com/cf5723a5647c667d19cd1d773c2226ac52fbea33a062d0a66fec1090ca665feb/68747470733a2f2f692e696d6775722e636f6d2f6a7239644e4e7a2e706e67)

Find the reason, the python code of placeholder should not execute before python environment ready.

**Comment by CollinsPeriodLee** [comment]
> Find the reason, the python code of placeholder should not execute before python environment ready.

Thank you for the notification and debugging!

**Comment by ihasdapie** [comment]
Thank you for the fix!
