### ISSUE TITLE
[bug] when press <Tab>, vi will be suspended

### ISSUE THREAD

**Issue by Freed-Wu** [neoclide/coc-snippets#280]
```vim
" $ uname -r
" 5.16.15-arch1-1
" $ has nvim
" ✔ nvim 0.6.1
" $ has python
" ✔ python 3.10.2
" $ cat test.vim
set runtimepath=$VIMRUNTIME
set runtimepath+=~/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release
set runtimepath+=~/.local/share/nvim/repos/github.com/honza/vim-snippets
let g:coc_snippet_next = '<Tab>'
let g:coc_snippet_prev = '<S-Tab>'
let g:coc_config_home = '.'
inoremap <silent> <TAB> <C-R>=coc#rpc#request('doKeymap', ['snippets-expand-jump', ''])<CR>
" $ cat coc-settings.json
" $ vi -u test.vim main.c
```

Press

```
iinc<C-N>
```

![Screenshot from 2022-03-26 21-01-07](https://user-images.githubusercontent.com/32936898/160240737-3d1f5a4c-0343-48eb-ac4e-2ccf98a76c3d.png)

Press `<Tab>`

```
zsh: suspended  vi -u test.vim main.c
```

## Expected Behaviour

Not suspend.

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim. You can use `coc#rpc#notify` instead or close the pum first.

**Comment by Freed-Wu** [comment]
This bug disappear in snippet `inc` but still exists in other snippets. e.g. 
In python, press `from<Tab>`:

```
from package| import module
```

press `matplotlib`

```
from matplotlib| import module
```

Then press `<Tab>`, expected behaviour is jump to `module`, but vi suspend.

**Comment by Freed-Wu** [comment]
I have found
```
ad2b000caafa7a0323270ec7708a36597a819628 is the first bad commit
```

**Comment by Freed-Wu** [comment]
No, the true first bad commit is before ad2b, I found 3 different incorrect behaviour:

1. Press `from<Tab>` will suspend
2. Press `from<Tab>matplotlib<Tab>` will suspend
2. Press `from<Tab>matplotlib<Tab>` will enter normal mode not select mode in word `module`

**Comment by chemzqm** [comment]
It's caused by notification send during request, already fixed on coc.nvim.
