### ISSUE TITLE
Issue with identifying '#' and regular expression trigger words

### ISSUE THREAD

**Issue by kevin61416** [neoclide/coc-snippets#330]
# Issue 1: Identifying '#' in snippets
In the `c.snippets` file, I noticed that triggers starting with `#` are not being recognized correctly in C files.  For example, `#ifndef`, `#if` in `c.snippets` both not works.  

Additionally, the `#v` snippet in my `sh.snippets` file is also not being recognized. However, the only exception is the Shebang `#!`, which is identified correctly.

Figure 1 - `#if` only has LSP sources:
<img width="477" alt="截圖 2023-05-28 01 53 31" src="https://github.com/neoclide/coc-snippets/assets/68954028/d324376d-937e-4bf7-afea-aa214546f16f">

Figure 2 - Other trigger words work fine:
<img width="669" alt="截圖 2023-05-28 01 50 27" src="https://github.com/neoclide/coc-snippets/assets/68954028/3b40a069-eacc-4f01-a7a4-fca618c27929">

# Issue 2: Ineffective regular expression trigger words
Trigger words defined with regular expressions are not working as expected too. For instance, in the `sh.snippets` file of UltiSnips, the trigger word `/wh(ile)?/` is recognized when I type 'wh', but 'while' does not trigger the snippet. Similarly, the trigger word `/case|sw(itch)?/` is identified correctly with 'case' but not with 'sw' or 'switch'.

Figure 3 - `wh` works well:
<img width="587" alt="截圖 2023-05-28 01 39 24" src="https://github.com/neoclide/coc-snippets/assets/68954028/e98c9c98-c705-4eec-a240-f470a7e3e22d">

Figure 4 - `while` not works:
<img width="331" alt="截圖 2023-05-28 01 40 14" src="https://github.com/neoclide/coc-snippets/assets/68954028/ebe66e9b-b931-47fa-8fac-4952d7ccdbaa">
  

Environment:
- Vim version: VIM - Vi IMproved 9.0 9001400
- Node version: v18.16.0
- coc.nvim version: 0.0.82-b7375d5f (January 30, 2023)
  

I would greatly appreciate any guidance or solutions you can provide to resolve these issues. Please let me know if you need any further information.

Thank you!

**Comment by kevin61416** [comment]
@chemzqm 
Still not works 🥲

For example,
`s#!` works, but `#!` not
<img width="164" alt="截圖 2023-09-07 21 23 21" src="https://github.com/neoclide/coc-snippets/assets/68954028/336d5a4f-8da3-4800-8940-e76af236542c">
<img width="343" alt="截圖 2023-09-07 21 25 42" src="https://github.com/neoclide/coc-snippets/assets/68954028/36b405f2-0b2c-4e2f-b71b-7d614778de9a">

**Comment by chemzqm** [comment]
You need to include `!` to configuration `"snippets.triggerCharacters"` for this case

**Comment by kevin61416** [comment]
I don't know whether the recent version update caused most of the UltiSnips to become ineffective and unable to load.
The output of `CocCommand snippets.editSnippets`:
<img width="717" alt="截圖 2023-09-07 22 11 08" src="https://github.com/neoclide/coc-snippets/assets/68954028/4448b4a4-d4e0-4a2e-abe2-7c698965fbda">

**Comment by chemzqm** [comment]
> I don't know whether the recent version update caused most of the UltiSnips to become ineffective and unable to load. The output of `CocCommand snippets.editSnippets`

Fixed on latest 3.1.8 version.

**Comment by kevin61416** [comment]
> You need to include ! to configuration "snippets.triggerCharacters" for this case

Still does not work, also some snippets use regular expressions not work either, for example:
```sh
snippet /wh(ile)?/ "while ... (done)" rb
while ${2:[[ ${1:condition} ]]}; do
	${0:${VISUAL}}
done
endsnippet

snippet /ift(est)?/ "if ... then (if)" rb
if ${2:[ ${1:condition} ]}; then
	${0:${VISUAL}}
fi
endsnippet

```

**Comment by chemzqm** [comment]
Snippet with regex trigger are not included in completeion menu.

**Comment by kevin61416** [comment]
> **Note**: python regex in snippet are converted to javascript regex, however, some regex patterns can't be supported by javascript, including `(?x)` `(?s)` `\Z` `(?(id/name)yes-pattern|no-pattern)`.

Thank you for the explanation! However, I believe this is a straightforward and simple regex that's compatible with both POSIX and JS. Could you consider adding support for this kind of simple regex? I think it would be very helpful!

**Comment by chemzqm** [comment]
> @chemzqm Still not works 🥲
> 
> For example, `s#!` works, but `#!` not 

There's bug

**Comment by chemzqm** [comment]
Fixed

**Comment by kevin61416** [comment]
Still not works 🥲, my coc-settings.json:
```json
{
    "snippets.triggerCharacters": ["!"]
}

**Comment by chemzqm** [comment]
> Still not works 🥲, my coc-settings.json:
> 
> ```json
> {
>     "snippets.triggerCharacters": ["!"]
> }
> ```

Should work when you type `!`

**Comment by kevin61416** [comment]
I've tried it, but it didn't work.
<img width="186" alt="截圖 2023-09-22 00 00 58" src="https://github.com/neoclide/coc-snippets/assets/68954028/c6fde11c-e371-4b24-ae66-3ebf9336de0d">

Snippets that start with English letters are all working properly.
<img width="321" alt="截圖 2023-09-22 00 00 48" src="https://github.com/neoclide/coc-snippets/assets/68954028/7aa63148-6791-4b90-bae0-6905ebb1dbab">
